#!/usr/bin/env bash
. script/env
set -xe

pip install --upgrade pip
python setup.py install
rm -rf dist
python setup.py sdist
python setup.py bdist_wheel --universal

pip install --upgrade twine
twine upload dist/*
