#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e

# Wait until the tensorflow-serving connection is up.
for port in $(seq 9001 9006); do
  n=0
  until [ $n -ge 10 ]
  do
    if [[ $(nc localhost $port -w 5 | wc -c) -ne 0 ]]; then break; fi
    n=$[$n+1]
    sleep 5
  done
done

# Run the tests and linting checks
PYTHONPATH="." pytest $ARGS
flake8 --max-line-length 50000 model_converters
