#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e

# Run the tests and linting checks
PYTHONPATH="." pytest --cov=./ -v -s $ARGS
flake8 --ignore E501,E741 model_converters tests

# Upload coverage for CI.
if [ -n "$CI" ]; then
  pip install codecov
  codecov
fi
